services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Optional: override environment variables here if needed.
      - FLASK_APP=app/server.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
